// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqx2CoRd1mii84ok6lkluRD9BjZ_LhAxk',
    appId: '1:539241520015:web:5496a2f2d9b9516f9609fa',
    messagingSenderId: '539241520015',
    projectId: 'zarvis-app-c4bd4',
    authDomain: 'zarvis-app-c4bd4.firebaseapp.com',
    storageBucket: 'zarvis-app-c4bd4.appspot.com',
    measurementId: 'G-JEKVJP33X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8hoAgqAVAizdj1GSrTtgL-YEZ09MWbw',
    appId: '1:892994009358:android:4821810be5c446a1567f5f',
    messagingSenderId: '892994009358',
    projectId: 'zarivs-21035',
    storageBucket: 'zarivs-21035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcypLhuxLtIP-UF7LWaQBlvpUtE5JROC8',
    appId: '1:892994009358:ios:cc4d8ebf3b74f24e567f5f',
    messagingSenderId: '892994009358',
    projectId: 'zarivs-21035',
    storageBucket: 'zarivs-21035.appspot.com',
    iosBundleId: 'com.example.zarvisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUDvx6_yLilHtZ1C5da2R1Hkr7hxmi4E8',
    appId: '1:539241520015:ios:49e6acb978db745a9609fa',
    messagingSenderId: '539241520015',
    projectId: 'zarvis-app-c4bd4',
    storageBucket: 'zarvis-app-c4bd4.appspot.com',
    iosBundleId: 'com.example.zarvisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqx2CoRd1mii84ok6lkluRD9BjZ_LhAxk',
    appId: '1:539241520015:web:ef0dc65b8da6a6189609fa',
    messagingSenderId: '539241520015',
    projectId: 'zarvis-app-c4bd4',
    authDomain: 'zarvis-app-c4bd4.firebaseapp.com',
    storageBucket: 'zarvis-app-c4bd4.appspot.com',
    measurementId: 'G-SZ93RY4STT',
  );

}